### PR TITLE
Create Pushti Depani.md

### PR DESCRIPTION
**Pull request by Pushti18**

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
Hi @Pushti18 ,
Please complete the https://github.com/DeCodeCafe/Onboarding-and-ToDo-List- in order to complete your onboarding!

**Comment by Pushti18** [comment]
Ya doing

**Comment by Rahulkhinchi03** [comment]
@Pushti18 any update?

**Comment by Pushti18** [comment]
Yes, it's done.

**Comment by Rahulkhinchi03** [comment]
I cannot see your file and changes.

**Comment by Pushti18** [comment]
Ok let me check it because i have updated is before 2 days

**Pull request closed without merging**
